name: CellMet
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - scipy
      - matplotlib
      - pandas
      - tables
      - jupyter
      - joblib
      - notebook
      - ipywidgets
      - pythreejs
      - ipyvolume
      - meshio
      - xarray
      - vtk
      - tifffile
      - scikit-image  # instead of 'skimage' which is an alias
      - scikit-learn
      - sparse
      - networkx
      - tqdm
